### PR TITLE
Restructure project layout to support use via CMake add_subdirectory

### PR DESCRIPTION
**Pull request by johannes-wolf**
To support building and linking this library via CMake `add_subdirectory`, restructure project layout and `CMakeLists.txt` file.

Also:
* Follow some CMake best-practices and use “target-level’ (`target_*`, …) commands.
* Enable CI for Pull-Requests.

### CODE REVIEW

**Comment by hrantzsch** [comment]
Looks good, thank you.
Unfortunately, I think the restructuring will break the coverage CI action (as we currently collect the source files for gcovr simply as "keychain.*"). Could you adjust this to the new folder structure as well?

**Comment by hrantzsch** [comment]
Another thing, it seems CI didn't run on the second commit (thus not revealing that coverage might be broken). [See here](https://github.com/hrantzsch/keychain/pull/23/checks?sha=b13f3968a46453f74b5fa560c08ba8ab906d1b22). Any idea why that is? My understanding was that the `on: pull_request` trigger should have caused a build when a commit is added.

**Comment by johannes-wolf** [comment]
Fixed the coverage filter paths to include everything under `src/` and `include/`. 
The build runs on the last commit only, if multiple commits are pushed, so I think this is fine.

**Comment by hrantzsch** [comment]
Great, thank you!

**Pull request merged**
